name: CI
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        run: echo test, and deploy your project.
        
  deploy-dev:
      runs-on: ubuntu-latest
      environment:
        name: dev
        url: 'diegosntts.com'
      needs: build
      steps:
        - name: Run a multi-line script
          run: echo Deploy Dev
  deploy-hmg:
      runs-on: ubuntu-latest
      environment:
        name: hmg
        url: 'diegosntts.com'
      needs: deploy-dev
      steps:
        - name: Run a multi-line script
          run: echo Deploy HMG
  deploy-prd:
      runs-on: ubuntu-latest
      environment:
        name: prd
        url: 'diegosntts.com'
      needs: deploy-hmg
      steps:
        - name: Run a multi-line script
          run: echo Deploy PRD
